services:
  nginx:
    build: .
    image: ftyszyx752/label-studio:${VERSION:-latest}
    restart: unless-stopped
    ports:
      - "8081:8085"
      # - "8082:8086"
    depends_on:
      - app
    environment:
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
    volumes:
      - ./mydata:/label-studio/data:rw
      - ./deploy/nginx/certs:/certs:ro
    command: nginx

  app:
    stdin_open: true
    tty: true
    build: .
    image: ftyszyx752/label-studio:${VERSION:-latest}
    restart: unless-stopped
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=${DB_NAME}
      - POSTGRE_USER=${DB_USER}
      - POSTGRE_PASSWORD=${DB_PASSWORD}
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=db
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
      - JSON_LOG=0
    volumes:
      - ./mydata:/label-studio/data:rw
    command: uwsgi

  db:
    image: pgautoupgrade/pgautoupgrade:13-alpine
    hostname: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./deploy/pgsql/certs:/var/lib/postgresql/certs:ro
